### ISSUE TITLE
Extracting/inserting data into an `IRISSpectrograph` object

### ISSUE THREAD

**Issue by byrdie** [sunpy/irispy#107]
Is there a succinct way to extract the raw data from the `IRISSpectrograph` object as a 4D `ndarray`?
I have implemented despiking routines that are designed to operate on simple `ndarrays`, so I need to be able to extract the data from the `IRISSpectrograph` object, execute the despiking routine, and then insert the data back into the `IRISSpectrograph` object.

Currently, I am extracting the data from the `IRISSpectrograph` objects something like
```python
obs = read_iris_spectrograph_level2_fits(path, self.iris_channel)

data_list = []
for dt in obs.data[self.iris_channel].data:
     data_list.append(dt.data)

data = np.stack(data_list)
```
but I feel as if there has to be a clearer way of doing this.

**Comment by tiagopereira** [comment]
You mean you want to merge all the wavelength windows into one dimension? This is not how the data are written in level 2 FITS files (each wavelength window is a FITS extension), so the data are never really a 4D array.

**Comment by DanRyanIrish** [comment]
Hi @byrdie and @tiagopereira.  From my reading of your question @byrdie, you want to combine data from one spectral window, but over multiple raster scans into a single 4D array?  In this case ```path``` represents multiple FITS files?  Is this correct?  Assuming it is, then following on from what @tiagopereira said, not only is the data from each window in a different FITS extension, but the data from each raster scan is in a different FITS file.  Therefore each raster scan array corresponds to a different set of coordinate transformations and so the ```IRISSpectrogramSequence``` (the ```obs.data[self.iris_channel]``` in your example) does not combine the data into a single array, but keeps them separate from raster scan to raster scan.

So the the short answer is the way you are doing it in your example is actually the best way.

**Comment by byrdie** [comment]
@DanRyanIrish you are correct, `path` represents multiple FITS files, so I am indeed trying to combine multiple raster scans into a single 4D array.
@tiagopereira and @DanRyanIrish, you both bring up good points of course, the 4D data should not be represented in a contiguous `ndarray` since it is both not presented that way (in the FITS files) and each raster position requires a different coordinate transformation.

However, it was pretty counter-intuitive for me to grasp that I needed to loop through the `IRISSpectrogramSequence` to simply extract all the raw data from the observation.
I suspect that many users including myself may not want to be constrained to the IRISpy box, and will need just the raw data for many image-processing sorts of tasks.
@DanRyanIrish and @tiagopereira, how would you guys feel about adding a function to the `NDCubeSequence` class to perform the 4D stacking operation in my example above?
I would be happy to take a crack at this modification if there are no objections, although it probably deserves some discussion as to how this should be implemented from a user-interface perspective.

**Comment by DanRyanIrish** [comment]
Hi @byrdie.  Actually having looked at it again, although conceptually there is no better way of combining the data from a sequence, there is a technically cleaner way that is a little faster if your sequence is very long.  That is, using list comprehension which turns your code into a one-liner.
```python
# Rename spectral window data for brevity.
sequence = obs.data[self.iris_channel]

# Make a single 4D array of data in sequence.
data = np.stack([cube.data for cube in sequence.data])
```
Likewise if you want to combine the data into a 3D array, say if you were thinking of the x axis of each cube as time, rather than longitude, you can use ```numpy.vstack```:
```python
# Make a 3D array
data = np.vstack([cube.data for cube in sequence.data])
```
And if you want to combine data from a single raster position over multiple raster scans, you can simply do:
```python
# Make a 3D array of data from 4th (zero-based) slit position
data = np.stack([cube[4] for cube in sequence.data])
```

It's great you're interested in contributing to IRISpy!  Since extracting the data from a Sequence object is in fact one line of code, I think adding a method to do that isn't the most valuable way to contribute.  I think the most useful contribution would be to focus on your valuable comment about how non-intuitive it initially was for you to access the data arrays in this way.  I think what is needed is a pull request adding a paragraph or section to the ndcube docs using this use case as a demonstration of how to explicitly access, extract and combine the data arrays.  And then add them back in afterwards.  This could be added to the ```NDCubeSequence``` section of the docs: https://github.com/sunpy/ndcube/blob/master/docs/ndcubesequence.rst

**Comment by tiagopereira** [comment]
@byrdie note that the IRIS mission already supports this type of 4D data structures, in the form of [level 3 files](http://iris.lmsal.com/itn26/iris_level3.html). But this implies converting the level 2 files to level 3 (about 2x larger because they are not scaled), and in your case I'm not sure if will lead to speed improvements. Plus IRISPy does not currently have a function to convert from level 2 to level 3. 

However, stacking all the rasters into one array can lead to memory problems. There are some datasets that will not fit in the memory of a typical workstation.

**Comment by byrdie** [comment]
@DanRyanIrish thanks for the great examples, using list comprehension really cleans up my original code.
I'm not sure I understand your last example, I assume you meant
```python
data = np.stack([cube[4].data for cube in sequence.data])
```
instead of
```python
data = np.stack([cube[4] for cube in sequence.data])
```
but wouldn't that make a 3D array from the 4th timestep at each raster position, instead of a 3D array of the 4th raster position over multiple scans?

I agree that since this can be easily expressed in one line that it would be unnecessary to add another method. Thanks for the suggestion to contribute to the documentation, I will take an action to update the file you linked with examples from our discussions here.

**Comment by tiagopereira** [comment]
IRIS level 2 FITS files are 16 bit integers. To get the correct units, these are multiplied by a factor and added a constant to become 32 bit floats (ie, scaled). The level 3 files are already saved as 32 bit floats, so they take twice the space.

**Comment by DanRyanIrish** [comment]
@byrdie, yes that's exactly what I meant.  Thanks for correcting me.  And yes, is would create a 3D array of the 4th raster positions since by selecting only one raster position, you are effectively getting rid of the x dimension.  But if you want to maintain the 4D-dimensionality, you can add in a dummy (length 1) dimension using ```np.newaxis```:
```python
>>> data.shape
(3, 4, 5)
>>> data = data[:, np.newaxis, :, :] # Equivalent to data[:, np.newaxis]
>>> data.shape
(3, 1, 4, 5)
```
